server:
  port: 10020

spring:
  application:
    name: order-server # 应用名称

eureka:
  client: # Eureka客户端配置，指向注册中心地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port} # 设置实例名称
    prefer-ip-address: true # 开启ip注册